config/routes.rb
Rails.application.routes.draw do

  get 'about/index'
  get 'about' => 'about#index'
  get 'repositories' => 'repositories#index'

  root 'repositories#index'

  resources :repositories
  resources :repositories do
    resources :branches
  end
  resources :branches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/models/repository.rb
class Repository < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About SciTech"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    @page_title = "Welcome to SciTech!"
end

app/controllers/repositories/branches_controller.rb
class Repositories::BranchesController < ApplicationController

  # To be repalce with the actual user!
  @page_title = "View branches / Add a new branch"

  def new
    @page_title = "Create a new branch"
    @repository = Repository.new
    @repository.branch = Branch.new
    @branch = @repository.branch
  end

  def create
    # @repository = Repository.new(repositoy_params)
    # @repository.save

    # redirect_to categories_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @page_title = "Features you have created! Lookin good!"
  end

  def show
    @page_title = "Title of the Repository/Branch"
  end

  # private 
  #   def repositoy_params
  #     params.require(:repository).permit(:name)
  #   end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  # To be repalce with the actual user!
  @page_title = "Welcome to SciTech!"

  def new
    @page_title = "New Repository"
    @repository = Repository.new
  end

  def create
    @repository = Repository.new(repositoy_params)
    @repository.save

    redirect_to repositories_path
  end

  def update
    @page_title = "Update Repository"
  end

  def edit
    @page_title = "Repository Details"
  end

  def destroy
  end

  def index
    @page_title = "Your innovations, Feel proud!"
    @repositories = Repository.all.collect {|repo| [repo.name, repo.id]}

  end

  def show
    @repo_id = params[:id]
    if Repository.exists?(params[:id])
      @repository = Repository.find(@repo_id)
      @page_title = @repository.name
    end
    if Branch.exists?("master")
      @repository.branch = Branch.find(repository_id = @repo_id)
    else
      @branch = Branch.new
    end
  end

  private 
    def repositoy_params
      params.require(:repository).permit(:name)
    end

    private 
    def branch_params
      params.require(:branch).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories/branches_helper.rb
module Repositories::BranchesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>SciTech</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to 'SciTech', root_path, class: "navbar navbar-brand"%>
      <div class="container">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="nav-item <%= 'active' if params[:controller] == 'repositories' %> ">
              <%= link_to 'Home', repositories_path, class: "nav-link"%>
            </li>
            <li class="nav-item <%= 'active' if params[:controller] == 'about' %> ">
              <%= link_to 'About', about_path, class: "nav-link"%>
            </li>
          </ul>
        </div>
        <div class="dropdown">
          <button class="btn btn-dark dropdown-toggle" type="button" id="addNew" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add New</button>
          <div class="dropdown-menu" aria-labelledby="addNew">
            <li><%= link_to 'Repository', new_repository_path, class: "dropdown-item" %></li>
          </div>
        </div>
      </div>
    </nav>

    <header>
      <div class="container text-center" style="padding-top:80px">
        <h1><small><%= @page_title ? @page_title : 'Welcome' %></small> </h1>
        <%= params[:action] %>
        <%= (params[:action] != 'new' || params[:action] != 'index') %>
      </div>
    </header>

    <section> 
      <% if params[:controller] == 'repositories' && params[:action] == 'show' %>
        <div class="row" style="width:100%">
          <div class="col-md-2" style="width:30%">
            <nav class="d-none d-md-block bg-light sidebar">
              <div class="sidebar-sticky">
                <ul class="nav flex-column">
                  <li><%= link_to 'Repository', new_repository_path, class: "dropdown-item" %></li>
                  <li><%= link_to 'Settings', new_repository_path, class: "dropdown-item" %></li>
                  <li><%= link_to 'Creators', new_repository_path, class: "dropdown-item" %></li>
                  <li><%= link_to 'Reports', new_repository_path, class: "dropdown-item" %></li>
                  <li><%= link_to 'Integrations', new_repository_path, class: "dropdown-item" %></li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                  <span>Saved reports</span>
                  <a class="d-flex align-items-center text-muted" href="#">
                    <span data-feather="plus-circle"></span>
                  </a>
                </h6>
                <ul class="nav flex-column mb-2">
                  <li><%= link_to 'Your Contributions', new_repository_path, class: "dropdown-item" %></li>
                </ul>
              </div>
            </nav>
          </div>
        <% end %>
        <div class="col-md-8 page-content">
          <%= yield %>
        </div>
      </div>
    </section>

    <footer>
      <div class="footer-copyright text-center py-1">
        <p>Copyright &copy; 2018, All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>

app/views/repositories/branches/create.html.erb
<h1>Repositories::Branches#create</h1>
<p>Find me in app/views/repositories/branches/create.html.erb</p>

app/views/repositories/branches/destroy.html.erb
<h1>Repositories::Branches#destroy</h1>
<p>Find me in app/views/repositories/branches/destroy.html.erb</p>

app/views/repositories/branches/edit.html.erb
<h1>Repositories::Branches#edit</h1>
<p>Find me in app/views/repositories/branches/edit.html.erb</p>

app/views/repositories/branches/index.html.erb
<h1>Repositories::Branches#index</h1>
<p>Find me in app/views/repositories/branches/index.html.erb</p>

app/views/repositories/branches/new.html.erb
<p>Find me in app/views/repositories/branches/new.html.erb</p>

<%= form_for @branch do |f| %>

    <div class="form-group">
        <%= f.label :basedon_branch %>
        <%= f.select :basedon_branch, Branch.all.collect {|branch| [branch.name, branch.id]}, {:include_blank => "Select Branch"}, class: 'form-control' %><br/>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br/>
    </div>

    <%= f.submit "Submit", disable_with: 'Submiting...', class: 'btn btn-success' %>
    <%= link_to 'Cancel', repositories_show_path(:id => @repository.id), class: 'btn btn-default cancel-button' %>

<% end %>

app/views/repositories/branches/show.html.erb
<h1>Repositories::Branches#show</h1>
<p>Find me in app/views/repositories/branches/show.html.erb</p>

app/views/repositories/branches/update.html.erb
<h1>Repositories::Branches#update</h1>
<p>Find me in app/views/repositories/branches/update.html.erb</p>

app/views/repositories/create.html.erb
<h1>Repositories#create</h1>
<p>Find me in app/views/repositories/create.html.erb</p>

app/views/repositories/destroy.html.erb
<h1>Repositories#destroy</h1>
<p>Find me in app/views/repositories/destroy.html.erb</p>

app/views/repositories/edit.html.erb
<h1>Repositories#edit</h1>
<p>Find me in app/views/repositories/edit.html.erb</p>

app/views/repositories/index.html.erb
<ul class="no-bullets">
    <% @repositories.each do |repo| %>
        <li><%= link_to repo[0], repository_path(:id => repo[1]), class: "list-group-item" %></li>
    <% end %>
</ul>

app/views/repositories/new.html.erb
<small>Find me in app/views/repositories/new.html.erb</small>

<%= form_for @repository do |f| %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %><br/>
    </div>

    <%= f.submit "Submit", disable_with: 'Submiting...', class: 'btn btn-success' %>
    <%= link_to 'Cancel', repositories_path, class: 'btn btn-default cancel-button' %>
<% end %>

app/views/repositories/show.html.erb
<%= form_for @branch do |f| %>

    <%= f.submit "New Branch", disable_with: 'Submiting...', class: 'btn btn-success' %>
    <%= link_to 'Cancel', repositories_path, class: 'btn btn-default cancel-button' %>

<% end %>

app/views/repositories/update.html.erb
<h1>Repositories#update</h1>
<p>Find me in app/views/repositories/update.html.erb</p>